Practica 8: Doctor Class Reference
Doctor Class Reference
#include <Doctor.h>
Public Member Functions
Doctor (int id=0, const std::string &username="", const std::string &password="", const std::string &name="", const std::string &email="", const std::string &specialty="")
std::string getSpecialty () const
void setSpecialty (const std::string &spec)
void showMenu () override
void displayInfo () const override
void confirmAttendance ()
void modifySchedule ()
void addNotesToAppointment ()
void viewMySchedule ()
Public Member Functions inherited from User
User (int id=0, const std::string &username="", const std::string &password="", const std::string &role="", const std::string &name="", const std::string &email="")
virtual ~User ()=default
int getId () const
std::string getUsername () const
std::string getPassword () const
std::string getRole () const
std::string getName () const
std::string getEmail () const
void setId (int newId)
void setName (const std::string &newName)
void setEmail (const std::string &newEmail)
Private Attributes
std::string specialty
Additional Inherited Members
Protected Attributes inherited from User
int id
std::string username
std::string password
std::string role
std::string name
std::string email
Detailed Description
Definition at line 8 of file Doctor.h.
Constructor & Destructor Documentation
Doctor()
Doctor::Doctor (int id = 0, const std::string & username = "", const std::string & password = "", const std::string & name = "", const std::string & email = "", const std::string & specialty = "")
Definition at line 4 of file Doctor.cpp.
    : User(id, username, password, "Doctor", name, email), specialty(specialty) {}
Member Function Documentation
addNotesToAppointment()
void Doctor::addNotesToAppointment ()
Definition at line 64 of file Doctor.cpp.
{
    std::cout << "\n--- Añadir Notas a Cita ---\n";
    std::cout << "Funcionalidad en desarrollo...\n";
    //TODO
}
Referenced by showMenu().
confirmAttendance()
void Doctor::confirmAttendance ()
Definition at line 52 of file Doctor.cpp.
{
    std::cout << "\n--- Confirmar Asistencia ---\n";
    std::cout << "Funcionalidad en desarrollo...\n";
    //TODO
}
Referenced by showMenu().
displayInfo()
void Doctor::displayInfo () const override virtual
Reimplemented from User.
Definition at line 46 of file Doctor.cpp.
{
    std::cout << "\n=== INFORMACIÓN DEL DOCTOR ===\n";
    User::displayInfo();
    std::cout << "Especialidad: " << specialty << "\n";
}
References User::displayInfo(), and specialty.
Referenced by showMenu().
getSpecialty()
std::string Doctor::getSpecialty () const inline
Definition at line 16 of file Doctor.h.
{ return specialty; }
References specialty.
modifySchedule()
void Doctor::modifySchedule ()
Definition at line 58 of file Doctor.cpp.
{
    std::cout << "\n--- Modificar Agenda ---\n";
    std::cout << "Funcionalidad en desarrollo...\n";
    //TODO
}
Referenced by showMenu().
setSpecialty()
void Doctor::setSpecialty (const std::string & spec) inline
Definition at line 17 of file Doctor.h.
{ specialty = spec; }
References specialty.
showMenu()
void Doctor::showMenu () override virtual
Implements User.
Definition at line 8 of file Doctor.cpp.
                      {
    int option;
    do {
        std::cout << "\n=== MENÚ DOCTOR ===\n";
        std::cout << "1. Confirmar Asistencia\n";
        std::cout << "2. Modificar Agenda\n";
        std::cout << "3. Añadir Notas a Cita\n";
        std::cout << "4. Ver Mi Agenda\n";
        std::cout << "5. Ver Mi Información\n";
        std::cout << "6. Cerrar Sesión\n";
        std::cout << "Seleccione una opción: ";
        std::cin >> option;
        switch(option) {
            case 1:
                confirmAttendance();
                break;
            case 2:
                modifySchedule();
                break;
            case 3:
                addNotesToAppointment();
                break;
            case 4:
                viewMySchedule();
                break;
            case 5:
                displayInfo();
                break;
            case 6:
                std::cout << "Cerrando sesión...\n";
                break;
            default:
                std::cout << "Opción no válida\n";
        }
    } while(option != 6);
}
References addNotesToAppointment(), confirmAttendance(), displayInfo(), modifySchedule(), and viewMySchedule().
viewMySchedule()
void Doctor::viewMySchedule ()
Definition at line 70 of file Doctor.cpp.
{
    std::cout << "\n--- Mi Agenda ---\n";
    std::cout << "Funcionalidad en desarrollo...\n";
    //TODO
}
Referenced by showMenu().
Member Data Documentation
specialty
std::string Doctor::specialty private
Definition at line 10 of file Doctor.h.
Referenced by displayInfo(), getSpecialty(), and setSpecialty().
The documentation for this class was generated from the following files:
import/Doctor.h
src/Doctor.cpp