Practica 8: Admin Class Reference
Admin Class Reference
#include <Admin.h>
Public Member Functions
Admin (int id=0, const std::string &username="", const std::string &password="", const std::string &name="", const std::string &email="")
void showMenu () override
void displayInfo () const override
void createDoctor ()
void assignSchedule ()
void viewDoctorsList ()
void viewAllUsers ()
Public Member Functions inherited from User
User (int id=0, const std::string &username="", const std::string &password="", const std::string &role="", const std::string &name="", const std::string &email="")
virtual ~User ()=default
int getId () const
std::string getUsername () const
std::string getPassword () const
std::string getRole () const
std::string getName () const
std::string getEmail () const
void setId (int newId)
void setName (const std::string &newName)
void setEmail (const std::string &newEmail)
Additional Inherited Members
Protected Attributes inherited from User
int id
std::string username
std::string password
std::string role
std::string name
std::string email
Detailed Description
Definition at line 8 of file Admin.h.
Constructor & Destructor Documentation
Admin()
Admin::Admin (int id = 0, const std::string & username = "", const std::string & password = "", const std::string & name = "", const std::string & email = "")
Definition at line 4 of file Admin.cpp.
    : User(id, username, password, "Administrator", name, email) {}
Member Function Documentation
assignSchedule()
void Admin::assignSchedule ()
Definition at line 62 of file AdminUtils.cpp.
                           {      //Me falla esto
    std::cout << "\n--- Asignar Agenda a Doctor ---\n";
    int idDoctor;
    std::string day, start, end;
    std::cout << "ID del Doctor: ";
    std::cin >> idDoctor;
    std::cout << "Día (Ej: Lunes): ";
    std::cin >> day;
    std::cout << "Hora inicio (HH:MM): ";
    std::cin >> start;
    std::cout << "Hora fin (HH:MM): ";
    std::cin >> end;
    Sistema& sys = Sistema::getInstance();
    bool ok = sys.assignScheduleToDoctor(idDoctor, day, start, end);
    if (ok)
        std::cout << "Agenda asignada correctamente.\n";
    else
        std::cout << "Error asignando agenda.\n";
}
References Sistema::assignScheduleToDoctor(), and Sistema::getInstance().
Referenced by showMenu().
createDoctor()
void Admin::createDoctor ()
Definition at line 10 of file AdminUtils.cpp.
{
    std::cout << "\n--- Crear Doctor ---\n";
    std::string username, password, name, email, specialty, telephone;
    std::cout << "Usuario: ";
    std::cin >> username;
    std::cout << "Contraseña: ";
    std::cin >> password;
    std::cout << "Nombre: ";
    std::cin.ignore();
    std::getline(std::cin, name);
    std::cout << "Correo: ";
    std::cin >> email;
    std::cout << "Especialidad: ";
    std::cin.ignore();
    std::getline(std::cin, specialty);
    std::cout << "Teléfono: ";
    std::cin >> telephone;
    Sistema& sys = Sistema::getInstance();
    bool ok = sys.registerUser(username, password, "Doctor",
                               name, email, specialty, telephone);
    if (ok)
        std::cout << "Doctor creado exitosamente.\n";
    else
        std::cout << "Error al crear doctor.\n";
}
References User::email, Sistema::getInstance(), User::name, User::password, Sistema::registerUser(), and User::username.
Referenced by showMenu().
displayInfo()
void Admin::displayInfo () const override virtual
Reimplemented from User.
Definition at line 5 of file AdminUtils.cpp.
{
    std::cout << "\n=== INFORMACIÓN DEL ADMINISTRADOR ===\n";
    User::displayInfo();
}
References User::displayInfo().
Referenced by showMenu().
showMenu()
void Admin::showMenu () override virtual
Implements User.
Definition at line 8 of file Admin.cpp.
                     {
    int option;
    do {
        std::cout << "\n=== MENÚ ADMINISTRADOR ===\n";
        std::cout << "1. Crear Doctor\n";
        std::cout << "2. Asignar Agenda a Doctor\n";
        std::cout << "3. Ver Lista de Doctores\n";
        std::cout << "4. Ver Todos los Usuarios\n";
        std::cout << "5. Ver Mi Información\n";
        std::cout << "6. Cerrar Sesión\n";
        std::cout << "Seleccione una opción: ";
        std::cin >> option;
        switch(option) {
            case 1:
                createDoctor();
                break;
            case 2:
                assignSchedule();
                break;
            case 3:
                viewDoctorsList();
                break;
            case 4:
                viewAllUsers();
                break;
            case 5:
                displayInfo();
                break;
            case 6:
                std::cout << "Cerrando sesión...\n";
                break;
            default:
                std::cout << "Opción no válida\n";
        }
    } while(option != 6);
}
References assignSchedule(), createDoctor(), displayInfo(), viewAllUsers(), and viewDoctorsList().
viewAllUsers()
void Admin::viewAllUsers ()
Definition at line 41 of file AdminUtils.cpp.
{
    std::cout << "\n--- Todos los Usuarios ---\n";
    Sistema& sys = Sistema::getInstance();
    auto users = sys.getAllUsers();
    if (users.empty()) {
        std::cout << "No hay usuarios registrados.\n";
        return;
    }
    for (const auto& u : users) {
        std::cout << "\nID: " << u->getId()
                  << "\nUsuario: " << u->getUsername()
                  << "\nRol: " << u->getRole()
                  << "\nNombre: " << u->getName()
                  << "\nEmail: " << u->getEmail()
                  << "\n------------------------\n";
    }
}
References Sistema::getAllUsers(), and Sistema::getInstance().
Referenced by showMenu().
viewDoctorsList()
void Admin::viewDoctorsList ()
Definition at line 87 of file AdminUtils.cpp.
{
    Sistema& sys = Sistema::getInstance();
    auto doctors = sys.getDoctorsList();
    if (doctors.empty()) {
        std::cout << "No hay doctores registrados.\n";
        return;
    }
    for (auto& d : doctors) {
        std::cout << "\nID: " << d->getId()
                  << "\nNombre: " << d->getName()
                  << "\n-----------------------\n";
    }
}
References Sistema::getDoctorsList(), and Sistema::getInstance().
Referenced by showMenu().
The documentation for this class was generated from the following files:
import/Admin.h
src/Admin.cpp
src/AdminUtils.cpp