Practica 8: Patient Class Reference
Patient Class Reference
#include <Patient.h>
Public Member Functions
Patient (int id=0, const std::string &username="", const std::string &password="", const std::string &name="", const std::string &email="", const std::string &telephone="")
std::string getTelephone () const
void setTelephone (const std::string &tel)
void showMenu () override
void displayInfo () const override
void requestAppointment ()
void viewMyAppointments ()
void cancelAppointment ()
Public Member Functions inherited from User
User (int id=0, const std::string &username="", const std::string &password="", const std::string &role="", const std::string &name="", const std::string &email="")
virtual ~User ()=default
int getId () const
std::string getUsername () const
std::string getPassword () const
std::string getRole () const
std::string getName () const
std::string getEmail () const
void setId (int newId)
void setName (const std::string &newName)
void setEmail (const std::string &newEmail)
Private Attributes
std::string telephone
Additional Inherited Members
Protected Attributes inherited from User
int id
std::string username
std::string password
std::string role
std::string name
std::string email
Detailed Description
Definition at line 8 of file Patient.h.
Constructor & Destructor Documentation
Patient()
Patient::Patient (int id = 0, const std::string & username = "", const std::string & password = "", const std::string & name = "", const std::string & email = "", const std::string & telephone = "")
Definition at line 4 of file Patient.cpp.
    : User(id, username, password, "Patient", name, email), telephone(telephone) {}
Member Function Documentation
cancelAppointment()
void Patient::cancelAppointment ()
Definition at line 60 of file Patient.cpp.
{
    std::cout << "\n--- Cancelar Cita ---\n";
    std::cout << "Funcionalidad en desarrollo...\n";
    //TODO
}
Referenced by showMenu().
displayInfo()
void Patient::displayInfo () const override virtual
Reimplemented from User.
Definition at line 42 of file Patient.cpp.
{
    std::cout << "\n=== INFORMACIÓN DEL PACIENTE ===\n";
    User::displayInfo();
    std::cout << "Teléfono: " << telephone << "\n";
}
References User::displayInfo(), and telephone.
Referenced by showMenu().
getTelephone()
std::string Patient::getTelephone () const inline
Definition at line 16 of file Patient.h.
{ return telephone; }
References telephone.
requestAppointment()
void Patient::requestAppointment ()
Definition at line 48 of file Patient.cpp.
{
    std::cout << "\n--- Solicitar Cita ---\n";
    std::cout << "Funcionalidad en desarrollo...\n";
    //TODO
}
Referenced by showMenu().
setTelephone()
void Patient::setTelephone (const std::string & tel) inline
Definition at line 17 of file Patient.h.
{ telephone = tel; }
References telephone.
showMenu()
void Patient::showMenu () override virtual
Implements User.
Definition at line 8 of file Patient.cpp.
                       {
    int option;
    do {
        std::cout << "\n=== MENÚ PACIENTE ===\n";
        std::cout << "1. Solicitar Cita\n";
        std::cout << "2. Ver Mis Citas\n";
        std::cout << "3. Cancelar Cita\n";
        std::cout << "4. Ver Mi Información\n";
        std::cout << "5. Cerrar Sesión\n";
        std::cout << "Seleccione una opción: ";
        std::cin >> option;
        switch(option) {
            case 1:
                requestAppointment();
                break;
            case 2:
                viewMyAppointments();
                break;
            case 3:
                cancelAppointment();
                break;
            case 4:
                displayInfo();
                break;
            case 5:
                std::cout << "Cerrando sesión...\n";
                break;
            default:
                std::cout << "Opción no válida\n";
        }
    } while(option != 5);
}
References cancelAppointment(), displayInfo(), requestAppointment(), and viewMyAppointments().
viewMyAppointments()
void Patient::viewMyAppointments ()
Definition at line 54 of file Patient.cpp.
{
    std::cout << "\n--- Mis Citas ---\n";
    std::cout << "Funcionalidad en desarrollo...\n";
    //TODO
}
Referenced by showMenu().
Member Data Documentation
telephone
std::string Patient::telephone private
Definition at line 10 of file Patient.h.
Referenced by displayInfo(), getTelephone(), and setTelephone().
The documentation for this class was generated from the following files:
import/Patient.h
src/Patient.cpp