Practica 8: Sistema Class Reference
Sistema Class Reference
Clase principal encargada de gestionar el sistema, incluyendo la base de datos, el inicio de sesión, registro de usuarios y administración de robots.
#include <Sistema.h>
Public Member Functions
Sistema ()
Constructor de la clase Sistema.
~Sistema ()
Destructor del sistema.
bool connectDatabase ()
Conecta el sistema a la base de datos SQLite.
bool registerUser (const std::string &username, const std::string &password, const std::string &role, const std::string &name="", const std::string &email="", const std::string &specialty="", const std::string &telephone="")
Registra un nuevo usuario en la base de datos.
std::unique_ptr< User > loginUser (const std::string &username, const std::string &password)
Autentica un usuario mediante sus credenciales.
void initializeRobots (int count)
Inicializa una cantidad específica de robots dentro del sistema.
void showRobotsStatus () const
Muestra el estado actual de todos los robots en el sistema.
void assignRobotTask (int robotId, int seconds, const std::string &taskType)
Asigna una tarea a un robot específico.
void assignAnyRobot (int seconds, const std::string &taskType)
Asigna una tarea al primer robot disponible.
void freeRobot (int robotId)
Libera un robot que haya terminado su trabajo.
std::vector< std::shared_ptr< User > > getDoctorsList () const
Obtiene la lista de doctores registrados.
std::vector< std::shared_ptr< User > > getAllUsers () const
Obtiene la lista completa de usuarios del sistema.
bool assignScheduleToDoctor (int idDoctor, const std::string &day, const std::string &start, const std::string &end)
Asigna un horario laboral a un médico.
Static Public Member Functions
static Sistema & getInstance ()
Obtiene la instancia única del sistema (Singleton).
Private Attributes
sqlite3 * db
Puntero al objeto de la base de datos SQLite.
std::vector< std::shared_ptr< Robot > > robots
Lista de robots administrados por el sistema.
Static Private Attributes
static Sistema * instance = nullptr
Instancia única del sistema (patrón Singleton).
Detailed Description
Clase principal encargada de gestionar el sistema, incluyendo la base de datos, el inicio de sesión, registro de usuarios y administración de robots.
Esta clase implementa el patrón Singleton para asegurar que solo exista una instancia global del sistema. Permite interactuar con la base de datos SQLite, registrar y autenticar usuarios, así como administrar las funcionalidades relacionadas con los robots.
Definition at line 24 of file Sistema.h.
Constructor & Destructor Documentation
Sistema()
Sistema::Sistema ()
Constructor de la clase Sistema.
Inicializa valores por defecto y prepara la estructura del sistema.
Definition at line 8 of file Sistema.cpp.
                 : db(nullptr) {
    connectDatabase();
}
References connectDatabase().
Referenced by getInstance().
~Sistema()
Sistema::~Sistema ()
Destructor del sistema.
Libera la memoria asociada y cierra la conexión con la base de datos.
Definition at line 12 of file Sistema.cpp.
                  {
    if (db) {
        sqlite3_close(db);
    }
}
References db.
Member Function Documentation
assignAnyRobot()
void Sistema::assignAnyRobot (int seconds, const std::string & taskType)
Asigna una tarea al primer robot disponible.
Parameters
seconds Duración de la tarea en segundos.
taskType Tipo de tarea.
Exceptions
std::runtime_error Si no hay robots disponibles.
Definition at line 145 of file Sistema.cpp.
{
    auto it = std::find_if(robots.begin(), robots.end(),
        [](const std::shared_ptr<Robot>& r) { return r->getState() == "Libre"; });
    if (it != robots.end()) {
        std::cout << "Asignando tarea al robot " << (*it)->getId() << "...\n";
        (*it)->assignTask(seconds, taskType);
    } else {
        std::cout << "No hay robots disponibles.\n";
    }
}
References robots.
Referenced by robotManagementMenu().
assignRobotTask()
void Sistema::assignRobotTask (int robotId, int seconds, const std::string & taskType)
Asigna una tarea a un robot específico.
Parameters
robotId ID del robot.
seconds Duración estimada de la tarea en segundos.
taskType Tipo de tarea asignada.
Exceptions
std::out_of_range Si el robotId no corresponde a ningún robot.
Definition at line 130 of file Sistema.cpp.
{
    auto it = std::find_if(robots.begin(), robots.end(),
        [robotId](const std::shared_ptr<Robot>& r) { return r->getId() == robotId; });
    if (it != robots.end()) {
        if ((*it)->getState() == "Libre") {
            (*it)->assignTask(seconds, taskType);
        } else {
            std::cout << "El robot " << robotId << " está ocupado.\n";
        }
    } else {
        std::cout << "No existe el robot con ID " << robotId << ".\n";
    }
}
References robots.
Referenced by robotManagementMenu().
assignScheduleToDoctor()
bool Sistema::assignScheduleToDoctor (int idDoctor, const std::string & day, const std::string & start, const std::string & end)
Asigna un horario laboral a un médico.
Parameters
idDoctor ID del médico.
day Día asignado.
start Hora de inicio.
end Hora de fin.
Returns
true si el horario fue asignado correctamente.
Exceptions
DatabaseError Si ocurre un error al ejecutar la consulta SQL.
Definition at line 75 of file SistemaUtils.cpp.
{
    const char* sql =
        "INSERT INTO SCHEDULE (ID_DOCTOR, DAY, START_TIME, END_TIME) VALUES (?, ?, ?, ?)";
    sqlite3_stmt* stmt;
    int rc = sqlite3_prepare_v2(db, sql, -1, &stmt, nullptr);
    if (rc != SQLITE_OK) {
        throw DatabaseError(std::string("sqlite3_prepare_v2: ") + sqlite3_errmsg(db));
    }
    sqlite3_bind_int(stmt, 1, idDoctor);
    sqlite3_bind_text(stmt, 2, day.c_str(), -1, SQLITE_STATIC);
    sqlite3_bind_text(stmt, 3, start.c_str(), -1, SQLITE_STATIC);
    sqlite3_bind_text(stmt, 4, end.c_str(), -1, SQLITE_STATIC);
    rc = sqlite3_step(stmt);
    sqlite3_finalize(stmt);
    if (rc != SQLITE_DONE) {
        throw DatabaseError(std::string("sqlite3_step: ") + sqlite3_errmsg(db));
    }
    return rc == SQLITE_DONE;
}
References db.
Referenced by Admin::assignSchedule().
connectDatabase()
bool Sistema::connectDatabase ()
Conecta el sistema a la base de datos SQLite.
Returns
true si la conexión fue exitosa.
false si ocurrió un error al abrir la base de datos.
Exceptions
DatabaseError Si SQLite devuelve un error de ejecución.
Definition at line 18 of file Sistema.cpp.
{
    int rc = sqlite3_open("appointment_system.db", &db);
    if (rc) {
        throw DatabaseError(std::string("sqlite3_open: ") + sqlite3_errmsg(db));
    }
    // Activar claves foráneas
    rc = sqlite3_exec(db, "PRAGMA foreign_keys = ON;", nullptr, nullptr, nullptr);
    if (rc != SQLITE_OK) {
        throw DatabaseError(std::string("PRAGMA foreign_keys: ") + sqlite3_errmsg(db));
    }
    return true;
}
References db.
Referenced by Sistema().
freeRobot()
void Sistema::freeRobot (int robotId)
Libera un robot que haya terminado su trabajo.
Parameters
robotId ID del robot a liberar.
Exceptions
std::out_of_range Si el robotId es inválido.
Definition at line 157 of file Sistema.cpp.
{
    auto it = std::find_if(robots.begin(), robots.end(),
        [robotId](const std::shared_ptr<Robot>& r) { return r->getId() == robotId; });
    if (it != robots.end()) {
        std::cout << "Liberando robot " << robotId << " manualmente.\n";
        // En una implementación real, aquí se forzaría la liberación
    } else {
        std::cout << "Robot no encontrado.\n";
    }
}
References robots.
getAllUsers()
std::vector< std::shared_ptr< User > > Sistema::getAllUsers () const
Obtiene la lista completa de usuarios del sistema.
Returns
Vector de punteros a objetos User.
Definition at line 35 of file SistemaUtils.cpp.
{
    std::vector<std::shared_ptr<User>> users;
    const char* sql =
        "SELECT ID, USERNAME, PASSWORD, ROLE, NAME, EMAIL, SPECIALTY, TELEPHONE FROM USER";
    sqlite3_stmt* stmt;
    int rc = sqlite3_prepare_v2(db, sql, -1, &stmt, nullptr);
    if (rc != SQLITE_OK) {
        throw DatabaseError(std::string("sqlite3_prepare_v2: ") + sqlite3_errmsg(db));
    }
    while (sqlite3_step(stmt) == SQLITE_ROW) {
        int id = sqlite3_column_int(stmt, 0);
        std::string username = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 1));
        std::string password = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 2));
        std::string role = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 3));
        std::string name = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 4));
        std::string email = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 5));
        std::string specialty = sqlite3_column_text(stmt, 6)
                               ? reinterpret_cast<const char*>(sqlite3_column_text(stmt, 6))
                               : "";
        std::string telephone = sqlite3_column_text(stmt, 7)
                               ? reinterpret_cast<const char*>(sqlite3_column_text(stmt, 7))
                               : "";
        if (role == "Doctor")
            users.push_back(std::make_shared<Doctor>(id, username, password, name, email, specialty));
        else if (role == "Patient")
            users.push_back(std::make_shared<Patient>(id, username, password, name, email, telephone));
        else if (role == "Administrator")
            users.push_back(std::make_shared<Admin>(id, username, password, name, email));
    }
    sqlite3_finalize(stmt);
    return users;
}
References db.
Referenced by Admin::viewAllUsers().
getDoctorsList()
std::vector< std::shared_ptr< User > > Sistema::getDoctorsList () const
Obtiene la lista de doctores registrados.
Returns
Vector de punteros a objetos User con rol de doctor.
Definition at line 6 of file SistemaUtils.cpp.
{
    std::vector<std::shared_ptr<User>> doctors;
    const char* sql =
        "SELECT ID, USERNAME, PASSWORD, NAME, EMAIL, SPECIALTY "
        "FROM USER WHERE ROLE = 'Doctor'";
    sqlite3_stmt* stmt;
    int rc = sqlite3_prepare_v2(db, sql, -1, &stmt, nullptr);
    if (rc != SQLITE_OK) {
        throw DatabaseError(std::string("sqlite3_prepare_v2: ") + sqlite3_errmsg(db));
    }
    while (sqlite3_step(stmt) == SQLITE_ROW) {
        int id = sqlite3_column_int(stmt, 0);
        std::string username = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 1));
        std::string password = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 2));
        std::string name = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 3));
        std::string email = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 4));
        std::string specialty = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 5));
        doctors.push_back(std::make_shared<Doctor>(id, username, password, name, email, specialty));
    }
    sqlite3_finalize(stmt);
    return doctors;
}
References db.
Referenced by Admin::viewDoctorsList().
getInstance()
static Sistema & Sistema::getInstance () inline static
Obtiene la instancia única del sistema (Singleton).
Si la instancia aún no existe, la crea automáticamente.
Returns
Referencia a la instancia única del sistema.
Definition at line 60 of file Sistema.h.
{
        if (!instance) instance = new Sistema();
        return *instance;
    }
References instance, and Sistema().
Referenced by Admin::assignSchedule(), Admin::createDoctor(), Admin::viewAllUsers(), and Admin::viewDoctorsList().
initializeRobots()
void Sistema::initializeRobots (int count)
Inicializa una cantidad específica de robots dentro del sistema.
Parameters
count Cantidad de robots a crear.
Definition at line 115 of file Sistema.cpp.
{
    robots.clear();
    for (int i = 1; i <= count; ++i) {
        robots.push_back(std::make_shared<Robot>(i));
    }
    std::cout << "Sistema de robots inicializado con " << count << " robots.\n";
}
References robots.
Referenced by main().
loginUser()
std::unique_ptr< User > Sistema::loginUser (const std::string & username, const std::string & password)
Autentica un usuario mediante sus credenciales.
Parameters
username Nombre de usuario.
password Contraseña del usuario.
Returns
Puntero único al objeto User correspondiente al rol detectado.
Exceptions
InvalidCredentialsError Si el usuario o la contraseña no coinciden.
DatabaseError Si ocurre un error al consultar la base de datos.
Definition at line 65 of file Sistema.cpp.
{
    sqlite3_stmt* stmt;
    const char* sql = "SELECT ID, USERNAME, PASSWORD, ROLE, NAME, EMAIL, SPECIALTY, TELEPHONE "
                      "FROM USER WHERE USERNAME = ? AND PASSWORD = ?";
    int rc = sqlite3_prepare_v2(db, sql, -1, &stmt, nullptr);
    if (rc != SQLITE_OK) {
        throw DatabaseError(std::string("sqlite3_prepare_v2: ") + sqlite3_errmsg(db));
    }
    sqlite3_bind_text(stmt, 1, username.c_str(), -1, SQLITE_STATIC);
    sqlite3_bind_text(stmt, 2, password.c_str(), -1, SQLITE_STATIC);
    rc = sqlite3_step(stmt);
    if (rc == SQLITE_ROW) {
        int id = sqlite3_column_int(stmt, 0);
        std::string db_username = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 1));
        std::string db_password = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 2));
        std::string role = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 3));
        std::string name = sqlite3_column_text(stmt, 4) ?
                          reinterpret_cast<const char*>(sqlite3_column_text(stmt, 4)) : "";
        std::string email = sqlite3_column_text(stmt, 5) ?
                           reinterpret_cast<const char*>(sqlite3_column_text(stmt, 5)) : "";
        std::string specialty = sqlite3_column_text(stmt, 6) ?
                               reinterpret_cast<const char*>(sqlite3_column_text(stmt, 6)) : "";
        std::string telephone = sqlite3_column_text(stmt, 7) ?
                               reinterpret_cast<const char*>(sqlite3_column_text(stmt, 7)) : "";
        sqlite3_finalize(stmt);
        // Crear el objeto correspondiente según el rol
        if (role == "Patient") {
            return std::make_unique<Patient>(id, db_username, db_password, name, email, telephone);
        } else if (role == "Doctor") {
            return std::make_unique<Doctor>(id, db_username, db_password, name, email, specialty);
        } else if (role == "Administrator") {
            return std::make_unique<Admin>(id, db_username, db_password, name, email);
        }
    } else if (rc == SQLITE_DONE) {
        sqlite3_finalize(stmt);
        throw InvalidCredentialsError();
    } else {
        sqlite3_finalize(stmt);
        throw DatabaseError(std::string("sqlite3_step: ") + sqlite3_errmsg(db));
    }
    sqlite3_finalize(stmt);
    return nullptr;
}
References db.
Referenced by loginUser().
registerUser()
bool Sistema::registerUser (const std::string & username, const std::string & password, const std::string & role, const std::string & name = "", const std::string & email = "", const std::string & specialty = "", const std::string & telephone = "")
Registra un nuevo usuario en la base de datos.
Parameters
username Nombre de usuario.
password Contraseña del usuario.
role Rol del usuario (e.g., "doctor", "patient", "admin").
name Nombre completo del usuario (opcional).
email Correo electrónico del usuario (opcional).
specialty Especialidad del doctor si aplica (opcional).
telephone Teléfono del usuario si aplica (opcional).
Returns
true si el registro fue exitoso.
false si el usuario no pudo registrarse.
Exceptions
DatabaseError Si ocurre un error en la ejecución de la consulta SQL.
Definition at line 32 of file Sistema.cpp.
{
    sqlite3_stmt* stmt;
    const char* sql = "INSERT INTO USER (USERNAME, PASSWORD, ROLE, NAME, EMAIL, SPECIALTY, TELEPHONE) "
                      "VALUES (?, ?, ?, ?, ?, ?, ?)";
    int rc = sqlite3_prepare_v2(db, sql, -1, &stmt, nullptr);
    if (rc != SQLITE_OK) {
        throw DatabaseError(std::string("sqlite3_prepare_v2: ") + sqlite3_errmsg(db));
    }
    sqlite3_bind_text(stmt, 1, username.c_str(), -1, SQLITE_STATIC);
    sqlite3_bind_text(stmt, 2, password.c_str(), -1, SQLITE_STATIC);
    sqlite3_bind_text(stmt, 3, role.c_str(), -1, SQLITE_STATIC);
    sqlite3_bind_text(stmt, 4, name.c_str(), -1, SQLITE_STATIC);
    sqlite3_bind_text(stmt, 5, email.c_str(), -1, SQLITE_STATIC);
    sqlite3_bind_text(stmt, 6, specialty.c_str(), -1, SQLITE_STATIC);
    sqlite3_bind_text(stmt, 7, telephone.c_str(), -1, SQLITE_STATIC);
    rc = sqlite3_step(stmt);
    sqlite3_finalize(stmt);
    if (rc != SQLITE_DONE) {
        if (rc == SQLITE_CONSTRAINT) {
            return false;
        }
        throw DatabaseError(std::string("sqlite3_step: ") + sqlite3_errmsg(db));
    }
    return true;
}
References db.
Referenced by Admin::createDoctor(), and registerNewUser().
showRobotsStatus()
void Sistema::showRobotsStatus () const
Muestra el estado actual de todos los robots en el sistema.
Definition at line 123 of file Sistema.cpp.
{
    std::cout << "\n=== ESTADO DE LOS ROBOTS ===\n";
    for (const auto& robot : robots) {
        std::cout << "Robot " << robot->getId() << " | Estado: " << robot->getState() << std::endl;
    }
}
References robots.
Referenced by robotManagementMenu().
Member Data Documentation
db
sqlite3* Sistema::db private
Puntero al objeto de la base de datos SQLite.
Definition at line 29 of file Sistema.h.
Referenced by assignScheduleToDoctor(), connectDatabase(), getAllUsers(), getDoctorsList(), loginUser(), registerUser(), and ~Sistema().
instance
Sistema * Sistema::instance = nullptr static private
Instancia única del sistema (patrón Singleton).
Definition at line 37 of file Sistema.h.
Referenced by getInstance().
robots
std::vector<std::shared_ptr<Robot> > Sistema::robots private
Lista de robots administrados por el sistema.
Definition at line 33 of file Sistema.h.
Referenced by assignAnyRobot(), assignRobotTask(), freeRobot(), initializeRobots(), and showRobotsStatus().
The documentation for this class was generated from the following files:
import/Sistema.h
src/Sistema.cpp
src/SistemaUtils.cpp